# Generated by Django 4.0.4 on 2022-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('message_count', models.IntegerField(blank=True, default=0, null=True)),
                ('days_activity', models.IntegerField()),
                ('last_date_activity', models.DateField()),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_message_info',
                'unique_together': {('user_id', 'chat_id')},
            },
        ),
    ]
